spring:
  application:
    name: activity
  redis:
    host: localhost
    password: sc_admin
  datasource:
    url: jdbc:postgresql://localhost:5432/look_activity
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8777
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: hgxljl
#    key-store-type: PKCS12
#    key-alias: tomcat
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/